buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
        // محرك خدمات جوجل
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

